"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import pb.ping_pb2 as _ping_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class GreeterStub:
    """service PingService {
        rpc GetFeature (Ping) returns (Feature) {}
    }
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> GreeterAsyncStub: ...
    SayHello: _grpc.UnaryUnaryMultiCallable[_ping_pb2.HelloRequest, _ping_pb2.HelloReply]
    """Sends a greeting"""
    SayHelloStreamReply: _grpc.UnaryStreamMultiCallable[_ping_pb2.HelloRequest, _ping_pb2.HelloReply]
    SayHelloBidiStream: _grpc.StreamStreamMultiCallable[_ping_pb2.HelloRequest, _ping_pb2.HelloReply]

@_typing.type_check_only
class GreeterAsyncStub(GreeterStub):
    """service PingService {
        rpc GetFeature (Ping) returns (Feature) {}
    }
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    SayHello: _aio.UnaryUnaryMultiCallable[_ping_pb2.HelloRequest, _ping_pb2.HelloReply]  # type: ignore[assignment]
    """Sends a greeting"""
    SayHelloStreamReply: _aio.UnaryStreamMultiCallable[_ping_pb2.HelloRequest, _ping_pb2.HelloReply]  # type: ignore[assignment]
    SayHelloBidiStream: _aio.StreamStreamMultiCallable[_ping_pb2.HelloRequest, _ping_pb2.HelloReply]  # type: ignore[assignment]

class GreeterServicer(metaclass=_abc_1.ABCMeta):
    """service PingService {
        rpc GetFeature (Ping) returns (Feature) {}
    }
    """

    @_abc_1.abstractmethod
    def SayHello(
        self,
        request: _ping_pb2.HelloRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_ping_pb2.HelloReply, _abc.Awaitable[_ping_pb2.HelloReply]]:
        """Sends a greeting"""

    @_abc_1.abstractmethod
    def SayHelloStreamReply(
        self,
        request: _ping_pb2.HelloRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_ping_pb2.HelloReply], _abc.AsyncIterator[_ping_pb2.HelloReply]]: ...

    @_abc_1.abstractmethod
    def SayHelloBidiStream(
        self,
        request_iterator: _MaybeAsyncIterator[_ping_pb2.HelloRequest],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_ping_pb2.HelloReply], _abc.AsyncIterator[_ping_pb2.HelloReply]]: ...

def add_GreeterServicer_to_server(servicer: GreeterServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
